[build]
builder = "nixpacks"
nixpacksVersion = "1.35.0"
buildCommand = "npm ci --ignore-scripts && npm run build && npx drizzle-kit migrate"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
